name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux-stable, macos-stable, windows-stable]
        include:
          - build: linux-stable
            os: ubuntu-latest
            rust: stable
          - build: macos-stable
            os: macos-latest
            rust: stable
          - build: windows-stable
            os: windows-latest
            rust: stable

    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            private-test-icals
            target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}

      - name: populate private-test-icals
        run: |
          ./populate-test-icals.sh
      
      - name: generate a test ical
        run: |
          cargo run --release --example generate_random > private-test-icals/generated.ical

      - name: Run Tests
        run: cargo test --all --locked
        env:
          RUST_BACKTRACE: 1

      - name: Clippy
        run: cargo clippy

      - name: Cargo fmt
        run: cargo fmt --all -- --check
